package swagger

import (
	"github.com/gin-gonic/gin"
	swaggerfiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "github.com/bsv-blockchain/spv-wallet-web-backend/docs" // docs package is generated by Swag CLI, we have to import it.
	router "github.com/bsv-blockchain/spv-wallet-web-backend/transports/http/endpoints/routes"
)

// NewHandler creates new endpoint handler.
func NewHandler() router.RootEndpoints {
	return router.RootEndpointsFunc(func(router *gin.RouterGroup) {
		router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerfiles.Handler))
	})
}
